#!/bin/bash

LOCK_FILE=/var/lock/subsys/centos_mirror
NETWORK_MIRROR=mirror.nsc.liu.se
DESTINATION_TOP=/export/data/mirror/CentOS

# check to make sure we're not already running
if [ -f $LOCK_FILE ]; then
    echo "CentOS mirror script already running." 1>&2
    exit 1
fi

touch $LOCK_FILE
rsync -avSHP --timeout=600 --delete --delete-delay --delay-updates --exclude "local*" $NETWORK_MIRROR::CentOS/ $DESTINATION_TOP
/bin/rm -f $LOCK_FILE

exit 0
