#!/usr/bin/env bash

readonly PROGNAME=$(basename "$0")
readonly LOCK_FILE=/var/lock/subsys/centos_mirror
readonly LOCK_FILE_FD=200
readonly NETWORK_MIRROR=mirror.liquidtelecom.com
readonly DESTINATION_TOP=/export/data/mirror/CentOS
readonly RSYNC_BIN=/usr/bin/rsync

lock() {
    local lock_file=$LOCK_FILE
    local lock_file_fd=$LOCK_FILE_FD

    # create the lock file
    eval "exec $lock_file_fd>$lock_file"

    # acquire the lock
    flock -n $lock_file_fd \
        && return 0 \
        || return 1
}

eexit() {
    local error_str="$@"

    echo $error_str
    exit 1
}

main() {
    lock \
        || eexit "Only one instance of $PROGNAME can run at one time."

    ${RSYNC_BIN} -avSHP --timeout=600 --delete --delete-delay --delay-updates --exclude "local*" $NETWORK_MIRROR::CentOS/ $DESTINATION_TOP
}

main
