#!/bin/bash

# Copyright (C) 2013 Alan Orth
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#
# interactive: Obtain interactive shell with slurm allocation
#
# Basically simulates:
#
#    salloc -n1 srun --x11 --pty bash

# defaults
readonly DEF_NUM_CPUS=1
readonly DEF_PARTITION=batch
readonly DEF_JOB_NAME=interactive

######

readonly PROGNAME=$(basename $0)
readonly ARGS="$@"

function usage() {
    cat <<-EOF
Usage: $PROGNAME [-c] [-p] [-J]

Optional arguments:
    -c: number of CPU cores to request (default: $DEF_NUM_CPUS)
    -p: partition to run job in (default: $DEF_PARTITION)
    -J: job name (default: $DEF_JOB_NAME)

Written by: Alan Orth <a.orth@cgiar.org>
EOF

    exit 0
}

function parse_options() {
    envsetup

    while getopts ":c:p:J:" opt; do
        case $opt in
            c)
                # make sure -c is passed a valid integer
                if ! [[ "$OPTARG" =~ ^[0-9]+$ ]]; then
                    usage
                fi

                NUM_CPUS=$OPTARG
                ;;
            p)
                PARTITION=$OPTARG
                ;;
            J)
                JOB_NAME=$OPTARG
                ;;
            \?|:)
                usage
                ;;
        esac
    done
}

function envsetup() {
    readonly SALLOC_BIN=/usr/bin/salloc
    readonly SRUN_BIN=/usr/bin/srun
    readonly INTERACTIVE_SHELL=/bin/bash

    # default is to request 1 CPU, unless more are requested
    if [[ $NUM_CPUS -gt $DEF_NUM_CPUS ]]; then
        SALLOC_OPTS="-n $NUM_CPUS"
    else
        SALLOC_OPTS="-n $DEF_NUM_CPUS"
    fi

    # check for a job name
    if [[ -n "$JOB_NAME" ]]; then
        SALLOC_OPTS="$SALLOC_OPTS -J $JOB_NAME"
    else
        SALLOC_OPTS="$SALLOC_OPTS -J $DEF_JOB_NAME"
    fi

    # see if the user specified a partition
    if [[ -n "$PARTITION" ]]; then
        SALLOC_OPTS="$SALLOC_OPTS -p $PARTITION"
    else
        SALLOC_OPTS="$SALLOC_OPTS -p $DEF_PARTITION"
    fi

    # check if we want X11
    if [[ -n "$DISPLAY" ]]; then
        SRUN_OPTS="--x11 --pty"
    else
        SRUN_OPTS="--pty"
    fi
}

# pass the shell's argument array to the parsing function
parse_options $ARGS

# setup the defaults
envsetup

$SALLOC_BIN $SALLOC_OPTS $SRUN_BIN $SRUN_OPTS $INTERACTIVE_SHELL
